"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Dillan Hong, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: dmh4484
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    # base case is
    if start >= len(nums):
        return target == 0

    # how to make a decision
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start + 1, nums, target)


def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    # base case
    if start >= len(nums):
        return target == 0

    # check if current is 6, if so include
    # recursive case is to either include or exclude current
    if nums[start] == 6:
        return group_sum_6(start + 1, nums, target - nums[start])
    return group_sum_6(start + 1, nums, target - nums[start]) or group_sum_6(
        start + 1, nums, target
    )


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    # base case
    if start >= len(nums):
        return target == 0

    # move by 2 indices
    # if element skipped, move to next one
    if group_no_adj(start + 2, nums, target - nums[start]):
        return True
    return group_no_adj(start + 1, nums, target)


def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 is 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0

    # check if multiple of 5
    # also check if value after is 1
    # recursive case is also to either include or exclude current
    if nums[start] % 5 == 0:
        if nums[start + 1] == 1:
            if group_sum_5(start + 2, nums, target - nums[start]):
                return True
        return group_sum_5(start + 1, nums, target - nums[start])
    return group_sum_5(start + 1, nums, target - nums[start]) or group_sum_5(
        start + 1, nums, target
    )


def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0

    # assign when clump starts and add up the values of clump
    # loop to check for succession and increasing size
    # recursive case includes or excludes clump
    sum_clump = nums[start]
    index = start + 1
    while index < len(nums) and nums[index] == nums[start]:
        sum_clump += nums[index]
        index += 1

    if group_sum_clump(index, nums, target - sum_clump) or group_sum_clump(
        index, nums, target
    ):
        return True
    return False


def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    # if total is odd, impossible to split evenly
    # target should be equal with both lists
    total = sum(nums)
    target = total // 2
    if total % 2 != 0:
        return False
    return split_array_helper(0, nums, target)


def split_array_helper(start, nums, target):
    """
    partition list into two groups with equal sums
    """
    # base case
    # recursive case include and exclude current num to reach target
    if target == 0:
        return True
    elif target < 0 or start >= len(nums):
        return False

    return split_array_helper(
        start + 1, nums, target - nums[start]
    ) or split_array_helper(start + 1, nums, target)


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    return split_odd_10_helper(0, nums, 0, 0)


def split_odd_10_helper(start, nums, sum_odd, times_10):
    """
    partition list into two groups: one sum odd, one multiple of 10
    """
    # base case
    if start == len(nums):
        return sum_odd % 2 != 0 and times_10 % 10 == 0
    return (
        split_odd_10_helper(start + 1, nums, sum_odd + nums[start], times_10)
        or split_odd_10_helper(start + 1, nums, sum_odd, times_10 + nums[start])
        or split_odd_10_helper(start + 1, nums, sum_odd, times_10)
    )


def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    # if total is odd, impossible to split evenly
    # target should be equal with both lists
    total = sum(nums)
    target = total // 2
    if total % 2 != 0 or len(nums) == 0:
        return False
    return split_53_helper(0, nums, target, 0, 0)


def split_53_helper(start, nums, target, sum_5, sum_3):
    """
    partition list into two groups: multiples of 5 and multiples of 3
    """
    # base case
    # check if multiple of 5 or 3, then include
    # if neither, include in any
    if start == len(nums):
        return sum_5 == target and sum_3 == target

    if nums[start] % 5 == 0:
        return split_53_helper(start + 1, nums, target, sum_5 + nums[start], sum_3)
    elif nums[start] % 3 == 0:
        return split_53_helper(start + 1, nums, target, sum_5, sum_3 + nums[start])
    return (
        split_53_helper(start + 1, nums, target, sum_5 + nums[start], sum_3)
        or split_53_helper(start + 1, nums, target, sum_5, sum_3 + nums[start])
        or split_53_helper(start + 1, nums, target, sum_5, sum_3)
    )
